### ISSUE TITLE
Payments with multiple items cause product earnings inaccuracies

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/edd-manual-purchases#13]
Manual Purchases doesn't support line-item pricing. Because of this, when a new payment is created, the price entered gets assigned to every item on the payment. This causes inaccuracies in the earnings stats **at the product level**. It also makes the payment details screen confusing because the total price doesn't match the total of the line item amounts.

##### Example manual purchase
![image](https://cloud.githubusercontent.com/assets/1254870/10551879/be619784-741d-11e5-9101-7a8d6d230382.png)

##### Payment details
![image](https://cloud.githubusercontent.com/assets/1254870/10551892/d3f749b8-741d-11e5-96a6-5f4d524c20c7.png)

In the above case, the total sale amount was $100, but each item's earnings total was increased by $100.

What do you think about line-item pricing as a feature and have the total price calculated from the line item totals? This would round out the feature set and fix the bug at the same time. Thoughts?

**Comment by pippinsplugins** [comment]
For 2.0, I'd like to completely rebuild the creation screen for this plugin to more closely the `View Order Details` screen. It should permit setting each and every amount variable.

**Comment by pippinsplugins** [comment]
This is fixed now.
