### ISSUE TITLE
Use EDD_Payment class

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/edd-manual-purchases#16]
EDD .2.5 is introducing `EDD_Payment`: https://github.com/easydigitaldownloads/Easy-Digital-Downloads/issues/2667

We should use it.

**Comment by chriscct7** [comment]
Well I agree it is a great use case for it here, unlike  FES, manual purchases doesn't prevent the extension from being activated on older EDD versions. This will throw a fatal error on EDD sites who have not updated yet. If you want to use this without back compat there really should be an FES style minimum version of EDD check

**Comment by chriscct7** [comment]
*While

**Comment by pippinsplugins** [comment]
:+1:

**Comment by pippinsplugins** [comment]
Added.
