### ISSUE TITLE
Not published to Packagist

### ISSUE THREAD

**Issue by retlehs** [easydigitaldownloads/edd-manual-purchases#25]
went to update this plugin and noticed that there's a `composer.json` file now (awesome!) — 90aa4f5add3ff5189e1edaebf906d61116fc85b2

could you please publish this project to https://packagist.org/?

in the meantime, pulling it in via composer requires:

```
  "repositories": [
    {
      "type": "vcs",
      "url": "https://github.com/easydigitaldownloads/edd-manual-purchases"
    }
  ],
  "require": {
    "johnpbloch/wordpress": "4.4",
    "easydigitaldownloads/EDD-Manual-Purchases": "1.9.3"
  }
```

**Comment by pippinsplugins** [comment]
I'll get it published next week.

**Comment by pippinsplugins** [comment]
Done!
