### ISSUE TITLE
Add support for setting item quantities

### ISSUE THREAD

**Issue by akyusa01** [easydigitaldownloads/edd-manual-purchases#28]
Ticket received requesting new feature:

"I am using your Manual Purchases extension and just encountered a limitation in that it does not allow me to specify the quantity of the item. While I can enter multiple items, our licensing works by tying X quantity to a key (as EDD is designed).

Can you toss this field [Quantity] into the Manual Purchases 'Create Payment' page when you get a chance?"

https://secure.helpscout.net/conversation/164779976/26384/?folderId=180504

**Comment by pippinsplugins** [comment]
I'll have this done in 2.0 (nearly done already).

**Comment by pippinsplugins** [comment]
This is complete.
