### ISSUE TITLE
Gateway Admin Label

### ISSUE THREAD

**Issue by flowdee** [easydigitaldownloads/edd-manual-purchases#29]
There are several cases where the payment gateway will be shown on the admin pages. 

Right now you are only forwarding the **manual_purchases** key hardcoded when creating a payment. Anyway to register the correct admin label as well? 

Might be an option to enhance the **edd_payment_gateways** handling. e.g.:

```
$default_gateway_info = array(
        'my_gateway_id' => array(
            'admin_label' => __('My Gateway', 'edd-btg'),
            'checkout_label' => false,
            'hidden' => true,
            'supports' => array(),
        ),
    );
```

**Comment by pippinsplugins** [comment]
In the upcoming 2.0 release, I've added support for selecting the gateway.

**Comment by flowdee** [comment]
Sounds great!

**Comment by flowdee** [comment]
think this can be closed due to the latest update, right @pippinsplugins ?

**Comment by pippinsplugins** [comment]
Yep!
