### ISSUE TITLE
Buyer ID or Email field should allow selecting existing users

### ISSUE THREAD

**Issue by brashrebel** [easydigitaldownloads/edd-manual-purchases#32]
The Buyer ID or email field in the payment creation form causes some issues. First, the UX leaves a little to be desired especially considering similar options elsewhere in EDD make this choice far easier, the primary example being the attach customer option on the edit payment screen. The second problem is that unexpected things occur if a user enters something invalid into the field. If someone mistakenly enters a string that doesn't match a user ID or user email, then instead of a new user being created or nothing being attached, the payment gets attached to a different user that already exists. I haven't yet figured out exactly what causes that but it's pretty strange.

Anyway, I believe this field should work similarly to the attach customer field in the edit payment screen. That way it will be easy to search for and select an existing user, or leave blank for guest.

**Comment by brashrebel** [comment]
Just made a PR that basically just puts in `EDD()->html->customer_dropdown()` instead. This is a simple improvement but can be taken a little farther. First off, it would make it so the field will now always pass user ID in so other types of user lookup are not necessary. This also doesn't resolve the problem of creating a payment for a user that doesn't currently exist but I believe that wasn't supported before. I guess that should be another issue.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by pippinsplugins** [comment]
This is close to working. I think we should hide the custom drop down when clicking New Customer, otherwise this can happen:
![screen shot 2016-04-22 at 12 19 58 pm](https://cloud.githubusercontent.com/assets/1034109/14749342/8ef80ab8-0884-11e6-9760-9a6d8ce8ad4f.png)

@brashrebel up for tackling that? If not, I can grab it.

**Comment by brashrebel** [comment]
I can do it.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by brashrebel** [comment]
Changed it so that this is seen first so an existing customer can be selected:
![screenshot 2016-04-27 07 20 53](https://cloud.githubusercontent.com/assets/4993131/14850680/b4c5a35a-0c48-11e6-8bc5-96aa2cf2ff7d.png)
and this is seen if the link is clicked so a customer can be created:
![screenshot 2016-04-27 07 21 03](https://cloud.githubusercontent.com/assets/4993131/14850690/c3866154-0c48-11e6-9a54-34355105d016.png)

Cool?
