### ISSUE TITLE
Don't require existing customer

### ISSUE THREAD

**Issue by brashrebel** [easydigitaldownloads/edd-manual-purchases#34]
I think it would be useful to allow a new customer to be created on the payment create screen instead of requiring only an existing customer. Just like on the edit payment screen where a new customer can be created. I'm also wondering if it should be possible to designate "guest" for a payment or just default to that if no customer is selected.

**Comment by pippinsplugins** [comment]
Makes sense to me!

**Comment by cklosowski** [comment]
I think I prefer we ALWAYS associate to a customer. Since you cannot make a purchase without getting a customer account created, we should never allow a manual record to be made without a customer record.

**Comment by pippinsplugins** [comment]
I agree but creating a new customer record during manual purchase creation is fine too.

**Comment by cklosowski** [comment]
Yes, I think that's being taken care of in #32...but if not, will make sure we get it in.

**Comment by cklosowski** [comment]
this has been completed and merged in #35 alongside of #32
