### ISSUE TITLE
User account ID not assigned to purchase meta (Software Licensing)

### ISSUE THREAD

**Issue by nosegraze** [easydigitaldownloads/edd-manual-purchases#45]
Not really sure if this should be here or with the Software Licensing extension. I experienced this problem with 2.0.1 so I'm not sure it exists in 2.0.2, but I didn't see anything in the changelog about it.

I created a manual purchase, assigned it to an existing customer (who is mapped to a user account), and the purchase was correctly assigned to the customer but the '_edd_sl_user_id' meta field wasn't populated with the user ID. This became an issue with this Software Licensing query:

    $meta_query = array(
		array(
				'key'   => '_edd_sl_user_id',
				'value' => $user_id
		)
    );

(used in EDD_Software_Licensing()->get_license_keys_of_user())

The _edd_sl_user_id field was set to 0 instead of the user's account ID. That means the license key didn't show up in the user's list of license keys.

I was able to fix this by opening up the payment in Payment History and immediately re-saving the purchase without any changes. But the ID should be added when the purchase is actually created.

**Comment by pippinsplugins** [comment]
I think this is a bug in the Software Licensing plugin. It needs to properly detect the user ID from the customer record.

Does the customer that you attached the purchase to show a user account being attached?

**Comment by nosegraze** [comment]
Yes it shows a user account being attached. And when I edited the purchase and re-saved it, it immediately mapped the user ID properly (without any changes to the purchase record). It just didn't assign during the manual purchase creation.

**Comment by pippinsplugins** [comment]
Ok good, so that's a Software Licensing bug that should be easy to fix. I'll open a new issue there.

**Comment by nosegraze** [comment]
Thanks!

**Comment by pippinsplugins** [comment]
See https://github.com/easydigitaldownloads/EDD-Software-Licensing/issues/520
