### ISSUE TITLE
Can't create $0 line item downloads within $0 payment

### ISSUE THREAD

**Issue by pderksen** [easydigitaldownloads/edd-manual-purchases#46]
When creating a $0 manual payment, I want to make sure the line items (downloads) are also $0 so that no dollar amounts affect any reports (total monthly sales, individual download sales, customer lifetime value, etc).

What I do now is change the download price to $0 and the total price to 0.00, like this:

![image](https://cloud.githubusercontent.com/assets/79667/15785581/dd77b2ac-296c-11e6-9e7f-d658b75b96ab.png)

Though the total sticks at $0, the download is still it's original price (in this case $149).

![image](https://cloud.githubusercontent.com/assets/79667/15785986/0e0ab37c-296f-11e6-8a56-91d5c8fcb7fb.png)

What I have to do now is go into the payment, add a $0 download of the same type, then remove the original download that had it's original price attached. Then it ends up looking like this:

![image](https://cloud.githubusercontent.com/assets/79667/15786137/d62e3c52-296f-11e6-9af7-9261c16e9fda.png)

Is there something that can be done so I can skip the last correction step? Thanks.

**Comment by pippinsplugins** [comment]
@pderksen this works fine for me. We must have fixed it somewhere along the road so closing.
