### ISSUE TITLE
Disable custom emails in PPE when "Send Receipt" is disabled

### ISSUE THREAD

**Issue by sumobi** [easydigitaldownloads/edd-manual-purchases#55]
When "Send the purchase receipt to the buyer?" is disabled and Per Product Emails is active, the custom emails from PPE are still sent. I propose adding in a check and removing the action in PPE when this option is disabled.

**Comment by sumobi** [comment]
I have tested, can someone else also?

**Comment by SDavisMedia** [comment]
Tested. All good here, @sumobi. 👍

**Comment by pippinsplugins** [comment]
Looks good.

**Comment by pippinsplugins** [comment]
@sumobi could you version bump and deploy `2.0.4`?

**Comment by sumobi** [comment]
Nice, thanks @SDavisMedia 

@pippinsplugins Sure can

**Comment by dipakcg** [comment]
@sumobi Tested as well and looks perfect.
