### ISSUE TITLE
Product selection limited to one search

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/edd-manual-purchases#61]
When creating a new payment, you have the ability to add products to the payment record. It appears that beyond the first, default row for adding a product, the dropdown's search functionality does not work.

To replicate, add a product to a payment (you can either search or select one of the populated list selections). Then click the **Add New** button to add a new product. Using that dropdown, try to search for a product. The search doesn't work.

**Comment by pippinsplugins** [comment]
@SDavisMedia I've tracked this down to a core issue. Can you test please? https://github.com/easydigitaldownloads/easy-digital-downloads/issues/5731

**Comment by SDavisMedia** [comment]
@pippinsplugins I've confirmed that EDD `issue/5731` fixes this on Manual Purchases `master`. :+1:

**Comment by pippinsplugins** [comment]
Sweet, thanks!
