### ISSUE TITLE
Integration with Auto Register

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/edd-manual-purchases#62]
When Auto Register is activated while creating a manual payment record, a new WP user should be created when the payment record is for a _new_ customer.

We should also add a setting to not create that new user.

**Comment by sunnyratilal** [comment]
PR opened and ready for testing on #63

**Comment by sunnyratilal** [comment]
@easydigitaldownloads/core-devs could I get a set of eyes on this please when possible? :)

**Comment by sunnyratilal** [comment]
Merged

**Comment by SDavisMedia** [comment]
Working well for me! :+!:

**Comment by sunnyratilal** [comment]
Thanks for testing @SDavisMedia :)
