### ISSUE TITLE
Connect user ID when present on customer

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/edd-manual-purchases#64]
If you create a payment with an existing customer, the User ID is not assigned on the payment. Conversely, if you create a payment but create a new customer, and that customer shares an email with an existing user it _does_ create the user_id post meta.

So essentially, what we need to happen is if you manually create a payment with an existing customer, and that customer has a User ID attached, we need to set the `user_id` on the payment as well.

**Comment by pippinsplugins** [comment]
Ready for testing.

**Comment by SDavisMedia** [comment]
Replicated on `master`. Creating a manual payment with an existing customer that has a user ID attached did _not_ add an `id` to the `user_info` array. On `issue/64`, it does. 👍
