### ISSUE TITLE
Purchases created with zeroed out prices save instead at full price.

### ISSUE THREAD

**Issue by danieliser** [easydigitaldownloads/edd-manual-purchases#69]
This has been this way for a long time. But I rarely create manual purchases so hasn't been hassle enough but finally wanted to report it. Figured someone else would but apparently not.

Every time I create new purchase manually with our core bundle ($199) and set the item price to 0 which correctly shows the total as $0 by the add item button, and then set the amount paid to 0 and then save, I have to immediately go back into purchase history and edit that payment as it saved with $199 paid and upped our daily totals etc.

We use several EDD extensions, the only 3rd party one though would be analytics.

Recurring, SL mainly + Stripe and a few for marketing purposes.

Let me know what other details you need or if you need a staging site to test on. The host is WP Engine for reference.

**Comment by pippinsplugins** [comment]
@danieliser enter `0.00` instead of `0` and it will work as expected.

**Comment by danieliser** [comment]
@pippinsplugins Cool, good to know. That said can we patch it so that 0 works too? Shouldn't it, is there any reason we couldn't just pad it with .00 or (float) $value it?

**Comment by pippinsplugins** [comment]
Happy to accept a patch :)

Not allowing `0` wasn't necessarily intentional. 0 is a hard value to deal with because we also want to support setting amounts to the default price. The design has always been "leave blank to fill automatically" or "enter manual price".

Doable: absolutely.
